### PR TITLE
[WIP] GH-87: Made initial changes to be able to run tests with external Git.

### PR DESCRIPTION
**Pull request by kittaakos**
Task: #87 

Although the work is still in progress, I wanted to verify the functionality with and without external Git.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

cc: @shiftkey

### CODE REVIEW

**Comment by kittaakos** [comment]
@shiftkey, are you using private Travis/Appveyor CIs? I was unable to access them.

**Comment by kittaakos** [comment]
I asked it too early, yes. As I can see, yes, it is a private Travis, but I can setup one on my fork. Never mind.

**Comment by kittaakos** [comment]
Unfortunately, the Travis CI failed. On my fork, it [failed with something else](https://travis-ci.org/kittaakos/dugite). Could you please provide some feedback on the failure? That would be a great help. Thank you!

**Comment by kittaakos** [comment]
@shiftkey, could you please look into the build failures and provide some feedback. That would be a great help. Thank you in advance! Meanwhile, I try to figure out what is wrong with the CI on my fork.

**Comment by shiftkey** [comment]
@kittaakos i'm chalking it up to Travis weirdness, everything looks fine now

**Comment by kittaakos** [comment]
Sorry, I have completely messed it up. I create a new one with only the external executables tests and close this PR.

**Pull request closed without merging**
