### PR TITLE
Allow Unsupported platforms to run, when Environment variables are set.

### PR DESCRIPTION
**Pull request by adamsteen**
I develop on OpenBSD and one of the packages i have taken an interest in, uses [surf](https://github.com/surf-build/surf) for continuous integration, relying on dugite for git support.

When i initially looked at the problem i thought i could set `GIT_EXEC_PATH` and `LOCAL_GIT_DIRECTORY` and things might work, but i hit some `throw new Error('Git not supported on platform: ' + process.platform)` errors.

With these changes and when the environment variables are set, the `Git not supported on platform` are not hit and dugite uses my installed git package, with the environment variables not set there is no functionally change.

I did the following changed.
Move platform check and Error into resolveEmbeddedGitDir, so if the
Environment variable 'LOCAL_GIT_DIRECTORY' is set, the error `throw new Error('Git not supported on platform: ' + process.platform)` is still executed.

Change path.join to set git-core and git to be if win32 else 'others' (with others being Unixes)

I didn't want to just target OpenBSD as i know of other developments using FreeBSD will also be impacted.

I know OpenBSD (and FreeBSD) are not supported and don't expect support, but by having these changes unsupported platforms have a chance of running.

[Edit] I have tested this change on OpenBSD and Windows.

### CODE REVIEW

**Comment by adamsteen** [comment]
@shiftkey Ping!

Is there anything i can do to help this along?

**Comment by shiftkey** [comment]
@adamsteen not really, just lacking bandwidth on my end to ponder the overall changes and ensure they don't affect the supported platforms.

I've got an open issue on the native toolchain to support FreeBSD https://github.com/desktop/dugite-native/issues/82 and we use Docker to build Git for ARM64 already so I'd love for someone more familiar with that flavour of OS to see if we can support that.

Would proper OpenBSD support help here, which is a way off, or are you just interested in the escape hatch?

**Comment by adamsteen** [comment]
@shiftkey proper OpenBSD would work also, but really i just want dugite to work in surf on OpenBSD so i can get CI setup.

**Comment by shiftkey** [comment]
@adamsteen this has been published to NPM as `v1.73.0`

**Comment by adamsteen** [comment]
@shiftkey thank you

**Pull request merged**
