### PR TITLE
[RFC] a better error parser

### PR DESCRIPTION
**Pull request by shiftkey**
This is a proposed solution for #124 and it does a bit more that just returning the raw captures, so let me explain the motivation behind it.

### Why not just return the captures?

Callers to `dugite` may not know that an expected error message will return additional data, without:

a) knowing the source regex associated with an enum value
b) knowing the right capture to use, because they're indexed by how they are matched in the regex

And what about regexes that don't return any captures? Or more complex types than strings?

### Returning something sensible

As we have to return _something_ alongside the error code - which I've tried to align with the v1 stuff but may change for compatibility reasons - we should just return an object. But we can actually leverage the TS type system to make things more structured.

**This is subject to change and probably a bit of renaming, but it works with the existing tests locally.**

Here's the new function for parsing errors:

```ts
export function parseError(stderr: string): GitErrorDetails | null {
  for (const [_, lookup] of GitErrorLookups.entries()) {
    const match = stderr.match(lookup.regexp)
    if (match) {
      const error = lookup.create(match)
      return error
    }
  }

  return null
}

```

`GitErrorDetails` looks like this at the moment:

```ts
export type GitErrorDetails =
  | CommonError
  | ProtectedBranchRequiredStatusError
  | BranchAlreadyExistsError
```

`CommonError` will be the one we most often use, as it just returns the enum (v1 callers should be able to port to this easily enough):

```ts
export type CommonError = {
  kind: CommonErrorKey
}
```

The other types defined here is how we can be more expressive with the error details:

```ts
export type ProtectedBranchRequiredStatusError = {
  kind: GitErrorKey.ProtectedBranchRequiredStatus
  status: string
}

export type BranchAlreadyExistsError = {
  kind: GitErrorKey.BranchAlreadyExists
  existingBranch: string
}
```

This gives us two things the raw regex doesn't support:

 - mapping captures to a more contextual name
 - richer type annotations - e.g. a field may be optional, or it may be a different type to string

### TODO

 - [ ] flush out some more compelling examples in the existing test suite
 - [ ] some better documentation
 - [ ] write a migration guide, using Desktop's migration steps
 - [ ] feedback
 - [ ] ???

### CODE REVIEW

**Comment by joshaber** [comment]
This looks great to me :sparkling_heart: :metal:

**Comment by ysabri** [comment]
Hi,

Sorry if I'm late with the comment. 

But can also the command + the args used to call the command be included in the error object. I find it very useful sometimes when debugging to know what args were used to call the command I want. 

For example if I'm iterating over a list of branches to get their logs and one of them errors out. The only way for me to find out which branch caused the error is to catch the error in the function and print out the branch name right there. This can get annoying since I can handle all errors in once place at a higher level if the information was included already.

Another thing I can think of is this can also be helpful in logging errors given that exec is asynchronous.

**Comment by shiftkey** [comment]
> But can also the command + the args used to call the command be included in the error object. I find it very useful sometimes when debugging to know what args were used to call the command I want, especially for common errors.

The current error parsing is only based on `stdout` or `stderr` - there needs to be a different way to surface the context for the Git operation. Feel free to open an issue so we can discuss this further.

**Comment by shiftkey** [comment]
Closing this out for the moment because I think I need to do some breaking changes to the `GitError` and `GitErrorRegexes` API before we can get into this advanced sort of scenario.

**Pull request closed without merging**
