### PR TITLE
Release 2.0.1 with Git 2.35.5

### PR DESCRIPTION
**Pull request by niik**
Updates our embedded Git to use 2.35.5 (and 2.35.5.windows.1).

### CODE REVIEW

**Review by tidy-dev — COMMENTED** [review]
Doesn't this usually include a bump in the package.json?

**Comment by niik** [comment]
> Doesn't this usually include a bump in the package.json?

Yeah but only after we publish to npm usually. I could do the `npm version minor` now and hold off on the publish though. I just didn't want to publish the tag here before CI had a chance to run. Gimme a sec

**Comment by niik** [comment]
The branch name here is going to be wrong but that's of no consequence, I accidentally made it 2.0.1 but it should have been 2.1.0 and that's what the package.json and tag will show

**Review by tidy-dev — APPROVED** [review]
✨

**Review by sergiou87 — APPROVED** [review]

**Pull request merged**
